apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-04
  labels:
    app: catalog-service-04
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service-04
  template:
    metadata:
      labels:
        app: catalog-service-04
    spec:
      containers:
        - name: catalog-service-04
          image: catalog-service-04
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://polar-postgres/polardb_catalog
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service-04
