apiVersion: v1
kind: Service
metadata:
  name: catalog-service-04
  labels:
    app: catalog-service-04
spec:
  type: ClusterIP
  selector:
    app: catalog-service-04
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001